name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: gpu

    steps:
    - uses: actions/checkout@v4

    - name: Create virtual environment
      run: |
        python3.11 -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip

    - name: Install package with dev dependencies
      run: |
        source .venv/bin/activate
        python -m pip install . -v
        python -m pip install psutil packaging wheel
        python -m pip install flash_attn==2.7.3 --no-build-isolation
        python -m pip install .[dev]  -v

    - name: Run tests
      run: |
        source .venv/bin/activate
        PYTORCH_NO_CUDA_MEMORY_CACHING=1 pytest -n 8 --junit-xml=test-results.xml --randomly-seed=12345 --reruns 10 --reruns-delay 60 --only-rerun "(CUDA.*out of memory|illegal memory access)"

    - name: Surface failing tests
      uses: pmeier/pytest-results-action@main
      with:
        path: test-results.xml
        summary: true
        display-options: fEX
        fail-on-empty: true
        title: Test results

    - name: Sanity-run training
      run: |
        source .venv/bin/activate
        ./scripts/test_train.sh
